# Generated by Django 4.1 on 2022-09-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, unique=True)),
                ('Author', models.CharField(max_length=70)),
                ('Summary', models.CharField(default='Short Text', max_length=200)),
                ('Content', models.TextField()),
                ('ImageName', models.TextField(default='name')),
                ('Image', models.ImageField(upload_to='')),
                ('Added_date', models.CharField(default='dd-mm-yyyy', max_length=20)),
                ('Category', models.CharField(default='cat', max_length=100)),
                ('Sub_Category', models.CharField(default='cat', max_length=100)),
                ('Views', models.IntegerField(default='00')),
            ],
        ),
    ]
