# Generated by Django 4.1 on 2022-09-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Added_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='news',
            name='Category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='Sub_Category',
            field=models.CharField(max_length=100),
        ),
    ]
