# Generated by Django 4.1 on 2022-09-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_category',
            name='Added_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='news_category',
            name='Created_By',
            field=models.CharField(default='Admin', max_length=40),
        ),
    ]
