# Generated by Django 4.1 on 2022-09-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category_App', '0002_alter_news_category_added_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_category',
            name='count',
            field=models.IntegerField(default='0'),
        ),
    ]
