# Generated by Django 4.1 on 2022-09-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category_App', '0003_news_category_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news_category',
            old_name='count',
            new_name='Count',
        ),
    ]
