# Generated by Django 4.1 on 2022-09-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sub_Category_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='Parent_Id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='Parent_Name',
            field=models.CharField(max_length=50),
        ),
    ]
